/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário logado, perfis e condomínios visíveis */
        get: operations["eu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categorias de arquivo, na ordem da tela */
        get: operations["categorias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Arquivos do mais recente para o mais antigo */
        get: operations["listarArquivos"];
        put?: never;
        /** Envia um arquivo (GESTOR ou ADMIN). O processamento segue em segundo plano. */
        post: operations["enviarArquivo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/ultimo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Último arquivo enviado (indicador no canto da tela) */
        get: operations["ultimoArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        /** Detalhe com conferências e saldos por fundo */
        get: operations["detalheArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/conteudo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        /** Arquivo original, exatamente como foi enviado */
        get: operations["conteudoArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/reprocessar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coloca o arquivo de novo na fila de leitura e, com o módulo Assistente ligado, de indexação (GESTOR ou ADMIN). Não duplica dados. */
        post: operations["reprocessarArquivo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/categoria": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Troca a categoria e reprocessa o arquivo (GESTOR ou ADMIN, RF-01.7). Mesma categoria não faz nada. */
        put: operations["alterarCategoriaArquivo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/painel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Números da tela inicial, do fluxo de caixa mais recente */
        get: operations["painel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/fundo-ordinario": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Confirma qual fundo é o ordinário do condomínio (GESTOR ou ADMIN) */
        put: operations["confirmarFundoOrdinario"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/contexto": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /**
         * Contexto do condomínio para montar a tela (módulos ligados). Qualquer perfil com acesso ao condomínio.
         * @description O menu "Assistente" depende de ASSISTENTE estar em modulosLigados (RF-10.2, RF-10.3). Ligar ou desligar vale
         *     no próximo carregamento, sem reinício. O modo de IA do assistente entra aqui na configuração de IA (ADR 0003).
         */
        get: operations["contextoCondominio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/modulos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Catálogo de módulos com o estado no condomínio (RF-10.1). Qualquer perfil com acesso; só leitura. */
        get: operations["listarModulos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/modulos/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                /** @description Código do módulo no catálogo (ex.: ASSISTENTE) */
                codigo: components["parameters"]["CodigoModulo"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Liga ou desliga um módulo no condomínio (só ADMIN, o administrador da plataforma no MVP; RF-10.2)
         * @description Grava o estado e um evento na trilha de ativação (só de inclusão), com motivo opcional. Pedir o estado que
         *     já vale não faz nada (nenhum evento). Ligar o ASSISTENTE coloca todos os arquivos do condomínio na fila de
         *     indexação depois da resposta (RF-10.4); desligar não apaga índice nem originais (RF-10.5).
         */
        put: operations["alterarModulo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/modulos/{codigo}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                /** @description Código do módulo no catálogo (ex.: ASSISTENTE) */
                codigo: components["parameters"]["CodigoModulo"];
            };
            cookie?: never;
        };
        /** Trilha de ativação do módulo no condomínio, da mais antiga para a mais recente (só ADMIN; RF-10.6) */
        get: operations["eventosModulo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/modulos/{codigo}/periodos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                /** @description Código do módulo no catálogo (ex.: ASSISTENTE) */
                codigo: components["parameters"]["CodigoModulo"];
            };
            cookie?: never;
        };
        /** Períodos ativos do módulo no condomínio, calculados da trilha (só ADMIN; RF-10.6) */
        get: operations["periodosModulo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/uso": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /**
         * Uso dos módulos no período, por função e por mês (só ADMIN no MVP; RF-09.7, Q17)
         * @description Datas no fuso de Brasília, fim incluído. Sem custo nesta fase.
         */
        get: operations["usoModulos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/uso/exportacao": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /**
         * Exporta os períodos ativos e o uso do período em Excel (só ADMIN; RF-10.6, RF-09.7)
         * @description Arquivo .xlsx com duas abas: "Períodos ativos" (os que tocam o período pedido) e "Uso por mês". Datas no
         *     horário de Brasília. Sem valores de cobrança nesta fase.
         */
        get: operations["exportarUsoModulos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** POs lidas do condomínio, da mais recente para a mais antiga (todos os perfis, RF-03.1.1) */
        get: operations["listarPrevisoes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        /** PO com linhas, conferências, avisos e pendências (todos os perfis, RF-03.1.1 e RF-03.1.2) */
        get: operations["detalhePrevisao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}/confirmacao": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirma a PO e o exercício (só ADMIN, RF-03.1.3; ciente da divergência, Q29)
         * @description Registra exercício, ata (ou "sem ata"), código efetivo das linhas com código impresso repetido e a ligação de
         *     cada linha de fundo (1.9.x) a um fundo do fluxo. Os valores lidos nunca são editados. PO lida com divergência
         *     de soma só é confirmada com cienteDivergencia e justificativa. Só uma PO vale para cada mês: sobreposição com
         *     PO confirmada exige reaprovacao (a anterior passa a SUBSTITUIDA a partir do início da nova).
         *     Fundo de reserva acima do teto (Conv. 20.1) gera achado ATENCAO; aprovação fora do 1º trimestre gera só aviso.
         */
        post: operations["confirmarPrevisao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}/depara": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        /**
         * De-para das contas do fluxo nesta versão da PO (todos os perfis, RF-03.1.4 e RF-03.1.13)
         * @description Contas do fluxo com débito no fundo Condomínio no exercício da PO, mais as contas que já têm de-para.
         *     Conta sem de-para tem estado nulo. Só CONFIRMADO entra no previsto × realizado.
         */
        get: operations["listarDepara"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}/depara/{conta}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
                /** @description Código da conta do fluxo como impresso (ex. 0028) */
                conta: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Admin escolhe o destino de uma conta (só ADMIN, RF-03.1.4 e RF-03.1.5)
         * @description Destino LINHA_PO aponta para uma linha de despesa da PO (grupos 1.1 a 1.8) pelo id, nunca pela conta da PO.
         *     Com confirmar nulo ou true, o de-para fica CONFIRMADO; com false, SUGERIDO. A trilha registra o destino e o
         *     estado anteriores e novos.
         */
        put: operations["definirDepara"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}/depara/lote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma ou recusa várias contas de uma vez (só ADMIN, RF-03.1.13), um evento por conta */
        post: operations["loteDepara"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}/depara/sugestoes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gera sugestões para as contas sem de-para (só ADMIN, RF-03.1.5), sem IA
         * @description Primeiro a versão anterior da PO (só o que estava confirmado; linha igual = mesmo código efetivo, conta e
         *     descrição), depois a comparação de nomes (sem dígitos, sem acento; nota mínima configurável; empate não
         *     sugere). Tudo entra SUGERIDO, com o motivo. Nenhuma conta é confirmada e nenhum número muda.
         */
        post: operations["sugerirDepara"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}/depara/planilha": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Carrega a planilha de sugestões (CSV "conta do fluxo;linha da PO"), só ADMIN (RF-03.1.5)
         * @description Formato do mapa do piloto, separado por ponto e vírgula, com ou sem cabeçalho, UTF-8 ou Windows-1252. Destino:
         *     código efetivo de uma linha de despesa, "AJUSTE (...)", "REALOCAR (...)" ou "TRANSFERENCIA (...)". Tudo entra
         *     SUGERIDO; conta já confirmada não muda; linha inválida é listada e não entra.
         */
        post: operations["planilhaDepara"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}/depara/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        /** Trilha do de-para (todos os perfis), só de inserção */
        get: operations["eventosDepara"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsto-realizado": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /**
         * Previsto × realizado do mês ou acumulado do exercício (todos os perfis, RF-03.1.6 a RF-03.1.11)
         * @description Calculado na consulta pela função pura CalculoPrevistoRealizado (versaoCalculo no resultado); nada é gravado.
         *     Realizado = débitos do fundo Condomínio (fundo ordinário) pelo de-para CONFIRMADO; ajustes, a realocar e sem
         *     linha da PO à parte; transferências entre fundos fora. Previsto do mês = soma das linhas 1.1 a 1.8 (Q30).
         *     Fundos ligados às linhas 1.9: arrecadação (recebimento de cota) × previsto. Mês sem fluxo, com dois fluxos,
         *     sem PO, com PO não confirmada ou sem fundo ordinário: situacao diz o porquê e os números ficam nulos.
         */
        get: operations["previstoRealizado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsto-realizado/evidencia": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Lançamentos que compõem um número do previsto × realizado (todos os perfis, RF-03.1.12) */
        get: operations["evidenciaPrevistoRealizado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContextoCondominio: {
            /** Format: uuid */
            condominioId: string;
            nome: string;
            /** @description Códigos dos módulos ligados (ex.: [ASSISTENTE]) */
            modulosLigados: string[];
        };
        ModuloDoCondominio: {
            codigo: string;
            nome: string;
            descricao: string;
            /** @description O que o módulo inclui (telas */
            inclui: string[];
            dependeDe: string[];
            /** @description Estado de um condomínio novo */
            ligadoPorPadrao: boolean;
            ligado: boolean;
            /**
             * Format: date-time
             * @description Desde quando está no estado atual. Nulo = nunca alterado (vale o padrão)
             */
            desde?: string | null;
            versaoCatalogo: number;
        };
        AlteracaoModulo: {
            ligado: boolean;
            /** @description Opcional (RF-10.6); em branco = não informado. Vai para a trilha de ativação */
            motivo?: string | null;
        };
        EventoModulo: {
            /** Format: uuid */
            id: string;
            modulo: string;
            ligadoAntes: boolean;
            ligadoDepois: boolean;
            usuario: string;
            /** Format: date-time */
            quando: string;
            /** @description Nulo quando não informado */
            motivo?: string | null;
        };
        PeriodoAtivo: {
            modulo: string;
            /**
             * Format: date-time
             * @description Nulo só se o módulo nasceu ligado por padrão, antes da trilha
             */
            inicio?: string | null;
            /**
             * Format: date-time
             * @description Nulo = ainda ligado
             */
            fim?: string | null;
            ligadoPor?: string | null;
            motivoLigar?: string | null;
            desligadoPor?: string | null;
            motivoDesligar?: string | null;
        };
        /**
         * @description busca_documentos = busca pela tela; chamada_mcp = buscar_documentos pelo MCP; indexacao = arquivo indexado; embeddings e pergunta = chat (entrega 3)
         * @enum {string}
         */
        FuncaoUso: "busca_documentos" | "chamada_mcp" | "indexacao" | "embeddings" | "pergunta";
        TotalUso: {
            /** @description AAAA-MM (só em porMes) */
            mes?: string;
            modulo: string;
            funcao: components["schemas"]["FuncaoUso"];
            /**
             * Format: int64
             * @description Número de registros (chamadas
             */
            quantidade: number;
            /** Format: int64 */
            tokensEntrada: number;
            /** Format: int64 */
            tokensSaida: number;
            /** Format: int64 */
            arquivos: number;
            /** Format: int64 */
            paginas: number;
        };
        UsoDoPeriodo: {
            /** Format: uuid */
            condominioId: string;
            /** Format: date */
            inicio: string;
            /** Format: date */
            fim: string;
            porFuncao: components["schemas"]["TotalUso"][];
            porMes: components["schemas"]["TotalUso"][];
        };
        /** @enum {string} */
        Categoria: "BALANCETE" | "EXTRATO" | "PO" | "CONTRATO" | "FOLHA" | "COMPROVANTE" | "ATA" | "CONVENCAO_RI" | "OUTROS";
        NovaCategoria: {
            categoria: components["schemas"]["Categoria"];
        };
        /** @enum {string} */
        StatusArquivo: "PENDENTE" | "PROCESSANDO" | "CONCLUIDO" | "PRECISA_REVISAO" | "FALHOU";
        CategoriaDto: {
            codigo: components["schemas"]["Categoria"];
            rotulo: string;
        };
        UsuarioLogado: {
            usuario: string;
            nome: string;
            perfis: ("USUARIO" | "GESTOR" | "ADMIN")[];
            condominios: {
                /** Format: uuid */
                id: string;
                nome: string;
            }[];
        };
        ArquivoResumo: {
            /** Format: uuid */
            id: string;
            categoria: components["schemas"]["Categoria"];
            categoriaRotulo: string;
            nome: string;
            /** Format: int64 */
            tamanhoBytes: number;
            status: components["schemas"]["StatusArquivo"];
            mensagem?: string | null;
            /** Format: date */
            periodoInicio?: string | null;
            /** Format: date */
            periodoFim?: string | null;
            totalLancamentos?: number | null;
            enviadoPor: string;
            /** Format: date-time */
            enviadoEm: string;
            /** Format: date-time */
            processadoEm?: string | null;
            /** @description Estado da indexação para a busca nos documentos (ADR 0003). Nulo ou ausente = arquivo ainda não indexado (enviado antes da busca ou com o módulo Assistente desligado; reprocessar ou ligar o módulo indexa). */
            indexacao?: components["schemas"]["IndexacaoArquivo"] | null;
        };
        /**
         * @description NA_FILA e INDEXANDO = em andamento; INDEXADO = aparece na busca; SEM_TEXTO = sem texto extraível (ex. PDF digitalizado); RETIRADO = fora da busca (exclusão lógica ou versão substituída); ERRO = falhou (ver motivo).
         * @enum {string}
         */
        SituacaoIndexacao: "NA_FILA" | "INDEXANDO" | "INDEXADO" | "SEM_TEXTO" | "RETIRADO" | "ERRO";
        IndexacaoArquivo: {
            situacao: components["schemas"]["SituacaoIndexacao"];
            /** @description Preenchido em SEM_TEXTO e ERRO */
            motivo?: string | null;
            /** @description Páginas (PDF), abas (Excel) ou 1 (Word) lidas */
            paginas?: number | null;
            /** @description Trechos gravados no índice */
            trechos?: number | null;
        };
        ArquivoDetalhe: {
            arquivo: components["schemas"]["ArquivoResumo"];
            sha256: string;
            conferencias: {
                codigo: string;
                descricao: string;
                ok: boolean;
                detalhe?: string | null;
            }[];
            fundos: {
                fundo: string;
                saldoAnterior: number;
                creditos: number;
                debitos: number;
                saldoAtual: number;
            }[];
        };
        Painel: {
            /** Format: uuid */
            arquivoId: string;
            arquivoNome: string;
            /** Format: date */
            periodoInicio: string;
            /** Format: date */
            periodoFim: string;
            saldoAnterior: number;
            entradas: number;
            saidas: number;
            saldoAtual: number;
            conferenciasComFalha: number;
            /**
             * @description Saldo acumulado do fundo ordinário (cartão "Saldo acumulado"). Com confirmado=false é só a sugestão
             *     (fundo com mais entradas no mês), que a tela mostra para o Gestor confirmar. Nulo quando não há sugestão.
             */
            fundoOrdinario: null | {
                /** Format: uuid */
                fundoId: string;
                fundo: string;
                confirmado: boolean;
                /** @description Nulo quando o fundo confirmado não está no relatório */
                saldoAtual: number | null;
            };
            fundos: {
                /** Format: uuid */
                fundoId: string;
                fundo: string;
                saldoAnterior: number;
                entradas: number;
                saidas: number;
                resultado: number;
                saldoAtual: number;
            }[];
            maioresDespesas: {
                /** Format: date */
                data: string;
                fundo: string;
                conta: string;
                historico: string;
                valor: number;
                pagina: number;
            }[];
        };
        /**
         * @description LIDA (aguarda confirmação), LIDA_COM_DIVERGENCIA (soma que não bate além da tolerância de arredondamento),
         *     CONFIRMADA (vale para os meses do exercício) e SUBSTITUIDA (trocada por reaprovação a partir de um mês).
         * @enum {string}
         */
        EstadoPrevisao: "LIDA" | "LIDA_COM_DIVERGENCIA" | "CONFIRMADA" | "SUBSTITUIDA";
        PrevisaoResumo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            arquivoId: string;
            arquivoNome?: string | null;
            sha256: string;
            estado: components["schemas"]["EstadoPrevisao"];
            /** @description Preenchida na confirmação (1 */
            versao?: number | null;
            titulo?: string | null;
            /** @description Como impresso (ex. "2026 / 2027") */
            exercicioImpresso?: string | null;
            /** @description AAAA-MM */
            exercicioInicio?: string | null;
            exercicioFim?: string | null;
            totalImpresso?: number | null;
            /** @description Soma das linhas dos grupos que não são fundos (usada nos cálculos) */
            previstoMes: number;
            /** Format: date-time */
            lidaEm: string;
            confirmadaPor?: string | null;
            /** Format: date-time */
            confirmadaEm?: string | null;
        };
        PrevisaoDetalhe: {
            previsao: components["schemas"]["PrevisaoResumo"];
            colunaOrcadoAnterior?: string | null;
            colunaOrcado?: string | null;
            /** @description Total impresso menos fundos impressos */
            previstoMesImpresso?: number | null;
            /** @description Diferença máxima tratada como arredondamento nesta leitura */
            toleranciaArredondamento: number;
            /** @description Mês a partir do qual vale a nova versão */
            substituidaDesde?: string | null;
            /** @description Dados informados pelo Admin; nulo antes da confirmação */
            confirmacao?: null | {
                /** Format: uuid */
                ataArquivoId?: string | null;
                semAta: boolean;
                /** Format: date */
                dataAprovacao?: string | null;
                cienteDivergencia: boolean;
                justificativaDivergencia?: string | null;
            };
            linhas: components["schemas"]["LinhaPo"][];
            conferencias: components["schemas"]["ConferenciaPo"][];
            avisos: components["schemas"]["AvisoPo"][];
            codigosRepetidos: {
                codigoImpresso: string;
                /** @description Os códigos efetivos dessas linhas já são distintos */
                resolvido: boolean;
                linhas: {
                    /** Format: uuid */
                    linhaId: string;
                    ordem: number;
                    descricao: string;
                    codigoEfetivo: string;
                }[];
            }[];
            /** @description Ligação das linhas de fundo (1.9.x) aos fundos do fluxo, feita na confirmação */
            fundos: {
                /** Format: uuid */
                linhaId: string;
                codigoEfetivo: string;
                descricao: string;
                orcado: number;
                /** Format: uuid */
                fundoId: string;
                fundo: string;
            }[];
            achados: {
                /** Format: uuid */
                id: string;
                regra: string;
                versaoRegra: string;
                /** @enum {string} */
                severidade: "INFORMATIVO" | "ATENCAO" | "CRITICO";
                competencia: string;
                descricao: string;
                /** @enum {string} */
                estado: "ABERTO";
            }[];
        };
        LinhaPo: {
            /**
             * Format: uuid
             * @description Identificador estável da linha (destino do de-para)
             */
            id: string;
            ordem: number;
            pagina: number;
            /** @enum {string} */
            tipo: "TOTAL" | "GRUPO" | "LINHA";
            codigoImpresso: string;
            /** @description Igual ao impresso; o Admin muda só quando o código se repete */
            codigoEfetivo: string;
            conta?: string | null;
            contaTexto?: string | null;
            /** @enum {string|null} */
            marca?: "RATEIO_A_PARTE" | "NEGOCIADA_ISENCAO" | "SEM_VALOR" | "VALOR_FIXO_SEM_REFERENCIA" | null;
            descricao: string;
            orcadoAnterior: number;
            orcado: number;
            /** @description Coluna "%" como lida; não entra em cálculo */
            percentualTexto?: string | null;
            observacoes?: string | null;
            /** @description Linha do grupo de fundos (precisa ser ligada a um fundo na confirmação) */
            linhaDeFundo: boolean;
            /** Format: uuid */
            arquivoId: string;
            sha256: string;
        };
        ConferenciaPo: {
            codigo: string;
            descricao: string;
            ok: boolean;
            detalhe?: string | null;
            /**
             * @description OK; ARREDONDAMENTO (diferença até a tolerância, só aviso); DIVERGENCIA; CODIGO_REPETIDO (pendência)
             * @enum {string}
             */
            classificacao: "OK" | "ARREDONDAMENTO" | "DIVERGENCIA" | "CODIGO_REPETIDO";
            /** @description Quando falhou */
            explicacao?: string | null;
        };
        AvisoPo: {
            /** @enum {string} */
            codigo: "ARREDONDAMENTO" | "DIVERGENCIA" | "CODIGO_REPETIDO" | "CONFIRMADA_COM_DIVERGENCIA" | "FORA_PRIMEIRO_TRIMESTRE" | "SEM_ATA" | "REGRA_NAO_AVALIADA";
            texto: string;
        };
        PedidoConfirmacao: {
            /** @description AAAA-MM */
            exercicioInicio: string;
            /** @description AAAA-MM */
            exercicioFim: string;
            /**
             * Format: uuid
             * @description Arquivo da categoria ATA; nulo com semAta
             */
            ataArquivoId?: string | null;
            semAta: boolean;
            /**
             * Format: date
             * @description Data da assembleia; obrigatória com ata
             */
            dataAprovacao?: string | null;
            /** @description Código distinto para linhas cujo código impresso se repete (mesmo grupo, ex. 1.3.2 → 1.3.25) */
            codigosEfetivos?: {
                /** Format: uuid */
                linhaId: string;
                codigo: string;
            }[];
            /** @description Cada linha de fundo (linhaDeFundo) ligada a um fundo do fluxo, distinto e que não seja o ordinário */
            fundos?: {
                /** Format: uuid */
                linhaId: string;
                /** Format: uuid */
                fundoId: string;
            }[];
            /** @default false */
            reaprovacao: boolean;
            /** @default false */
            cienteDivergencia: boolean;
            /** @description Obrigatória com cienteDivergencia */
            justificativa?: string | null;
        };
        /**
         * @description Linha da PO; ajuste (não é despesa); meio de pagamento a realocar (RF-02B); transferência entre fundos
         * @enum {string}
         */
        TipoDestino: "LINHA_PO" | "AJUSTE" | "A_REALOCAR" | "TRANSFERENCIA";
        /** @enum {string} */
        EstadoDepara: "SUGERIDO" | "CONFIRMADO" | "RECUSADO";
        /** @enum {string} */
        OrigemDepara: "VERSAO_ANTERIOR" | "PLANILHA" | "NOME" | "ADMIN";
        /**
         * @description PENDENTES = sem de-para confirmado (sem de-para, sugerido ou recusado)
         * @enum {string}
         */
        FiltroDepara: "TODAS" | "PENDENTES" | "SUGERIDO" | "CONFIRMADO" | "RECUSADO" | "SEM_DEPARA" | "IGUAIS_VERSAO_ANTERIOR";
        DestinoDepara: {
            tipo: components["schemas"]["TipoDestino"];
            /**
             * Format: uuid
             * @description Só com LINHA_PO
             */
            linhaId?: string | null;
            /** @description Código efetivo da linha */
            codigo?: string | null;
            descricao?: string | null;
            /** @description Texto do destino especial */
            detalhe?: string | null;
            /** @description Ex. "1.7.8 Material hidráulico" ou "AJUSTE (estorno)" */
            texto: string;
        };
        ContaDepara: {
            /** @description Código da conta do fluxo como impresso */
            conta: string;
            /** @description Nome como impresso no fluxo */
            nome?: string | null;
            /** @description Débitos do fundo Condomínio no exercício da PO */
            lancamentos: number;
            debitos: number;
            destino?: null | components["schemas"]["DestinoDepara"];
            /** @description Nulo = sem de-para */
            estado?: null | components["schemas"]["EstadoDepara"];
            origem?: null | components["schemas"]["OrigemDepara"];
            /** @description Nomes comparados */
            motivo?: string | null;
            igualVersaoAnterior: boolean;
            atualizadoPor?: string | null;
            /** Format: date-time */
            atualizadoEm?: string | null;
        };
        DeparaLista: {
            /** Format: uuid */
            previsaoId: string;
            versao?: number | null;
            /** @description Sempre sobre todas as contas, sem o filtro ("N de M contas confirmadas") */
            resumo: {
                contas: number;
                confirmadas: number;
                sugeridas: number;
                recusadas: number;
                semDepara: number;
            };
            contas: components["schemas"]["ContaDepara"][];
        };
        PedidoDestino: {
            tipo: components["schemas"]["TipoDestino"];
            /**
             * Format: uuid
             * @description Obrigatória com LINHA_PO
             */
            linhaId?: string | null;
            detalhe?: string | null;
            /** @description Nulo ou true confirma; false deixa SUGERIDO */
            confirmar?: boolean | null;
        };
        PedidoLote: {
            /** @enum {string} */
            acao: "CONFIRMAR" | "RECUSAR";
            contas: string[];
        };
        ContaIgnorada: {
            conta: string;
            motivo: string;
        };
        ResultadoLote: {
            alteradas: number;
            ignoradas: components["schemas"]["ContaIgnorada"][];
        };
        ResultadoSugestoes: {
            criadas: number;
            daVersaoAnterior: number;
            peloNome: number;
            semSugestao: {
                conta: string;
                nome?: string | null;
                motivo: string;
            }[];
        };
        ResultadoPlanilha: {
            aceitas: number;
            ignoradas: components["schemas"]["ContaIgnorada"][];
            recusadas: {
                linha: number;
                conteudo: string;
                motivo: string;
            }[];
        };
        EventoDepara: {
            /** Format: uuid */
            id: string;
            conta: string;
            nome?: string | null;
            /** @enum {string} */
            acao: "SUGERIDO" | "CONFIRMADO" | "RECUSADO" | "ALTERADO";
            usuario: string;
            /** Format: date-time */
            em: string;
            destinoAnterior?: string | null;
            estadoAnterior?: null | components["schemas"]["EstadoDepara"];
            destinoNovo: string;
            estadoNovo: components["schemas"]["EstadoDepara"];
            origem: components["schemas"]["OrigemDepara"];
            motivo?: string | null;
        };
        PrevistoRealizado: {
            /** @description Versão das regras do cálculo usada nesta resposta */
            versaoCalculo: string;
            /** @description AAAA-MM ou "acumulado" */
            periodo: string;
            /** @enum {string} */
            situacao: "CALCULADO" | "SEM_PO" | "PO_NAO_CONFIRMADA" | "SEM_FUNDO_ORDINARIO" | "SEM_FLUXO" | "DOIS_FLUXOS";
            /** @description Por que não há números (situação diferente de CALCULADO) */
            mensagem?: string | null;
            po?: null | {
                /** Format: uuid */
                id: string;
                versao?: number | null;
                estado: components["schemas"]["EstadoPrevisao"];
                /** Format: uuid */
                arquivoId: string;
                arquivoNome?: string | null;
                sha256: string;
                exercicioInicio?: string | null;
                exercicioFim?: string | null;
            };
            /** @description No acumulado, os meses do exercício; no mês, só ele. Números só com COM_FLUXO */
            meses: {
                mes: string;
                /** @enum {string} */
                situacao: "COM_FLUXO" | "SEM_FLUXO" | "DOIS_FLUXOS";
                fluxos: components["schemas"]["FluxoUsado"][];
                previsto?: number | null;
                despesaRealizada?: number | null;
                excesso?: number | null;
                percentualExcesso?: number | null;
                acimaDoLimite?: boolean | null;
            }[];
            mesesSomados: string[];
            /** @description Meses sem fluxo antes do último mês com fluxo */
            mesesSemFluxo: string[];
            mesesComDoisFluxos: string[];
            depara?: null | {
                /** @description Contas com débito no fundo Condomínio no período */
                contas: number;
                confirmadas: number;
                semDeparaConfirmado: number;
            };
            /** @description Há valor a realocar ou sem linha da PO */
            provisorio: boolean;
            totais?: null | {
                previstoMes: number;
                /** @description Previsto do mês × meses somados */
                previsto: number;
                /** @description Em linhas + a realocar + sem linha da PO */
                despesaRealizada: number;
                emLinhas: number;
                diferenca: number;
                /** @description % com 1 casa; nulo com previsto zero */
                execucao?: number | null;
                /** @description Previsto do mês × meses do exercício (referência) */
                previstoExercicio: number;
            };
            grupos: components["schemas"]["GrupoPrevistoRealizado"][];
            ajustes?: null | components["schemas"]["BlocoPrevistoRealizado"];
            aRealocar?: null | components["schemas"]["BlocoPrevistoRealizado"];
            semLinhaPo?: null | components["schemas"]["BlocoPrevistoRealizado"];
            conferencia?: null | {
                debitosDoFundo: number;
                lancamentos: number;
                despesaRealizada: number;
                ajustes: number;
                transferencias: number;
                confere: boolean;
            };
            /** @description Regra dos 20% (Conv. 16.2), só no mês */
            regra20?: null | {
                regra: string;
                versaoRegra: string;
                limitePercentual: number;
                previstoMes: number;
                /** @description Soma das diferenças positivas */
                excesso: number;
                percentual: number;
                /** @description Em reais */
                limite: number;
                linhasAcima: number;
                linhas: {
                    /** Format: uuid */
                    linhaId: string;
                    codigo: string;
                    descricao: string;
                    excesso: number;
                }[];
                aRealocar: number;
                semLinhaPo: number;
                /** @description Excesso + a realocar + sem linha da PO */
                cenarioMaximo: number;
                percentualCenarioMaximo?: number | null;
                provisorio: boolean;
                acimaDoLimite: boolean;
            };
            fundos: {
                /** Format: uuid */
                fundoId?: string | null;
                /** @description Nome impresso no fluxo */
                fundo?: string | null;
                /** Format: uuid */
                linhaId?: string | null;
                linhaCodigo?: string | null;
                /** @enum {string} */
                situacao: "COMPARADO" | "SEM_PREVISTO_NA_PO" | "LINHA_SEM_FUNDO" | "REPROCESSAR_FLUXO";
                previsto?: number | null;
                arrecadado?: number | null;
                diferenca?: number | null;
                execucao?: number | null;
                creditos?: number | null;
                debitos?: number | null;
            }[];
            avisos: {
                codigo: string;
                texto: string;
            }[];
        };
        FluxoUsado: {
            /** Format: uuid */
            arquivoId: string;
            nome: string;
            sha256: string;
            /** Format: date */
            periodoInicio?: string | null;
            /** Format: date */
            periodoFim?: string | null;
            /** Format: date-time */
            enviadoEm?: string | null;
            enviadoPor?: string | null;
        };
        GrupoPrevistoRealizado: {
            /** Format: uuid */
            linhaId: string;
            codigo: string;
            descricao: string;
            /** @description Soma das linhas (Q30) */
            previsto: number;
            realizado: number;
            diferenca: number;
            execucao?: number | null;
            linhas: {
                /** Format: uuid */
                linhaId: string;
                codigo: string;
                descricao: string;
                conta?: string | null;
                /** @enum {string|null} */
                marca?: "RATEIO_A_PARTE" | "NEGOCIADA_ISENCAO" | "SEM_VALOR" | "VALOR_FIXO_SEM_REFERENCIA" | null;
                observacoes?: string | null;
                pagina: number;
                previsto: number;
                realizado: number;
                diferenca: number;
                execucao?: number | null;
                /** @description Contas do fluxo com de-para confirmado para a linha */
                contasFluxo: string[];
                lancamentos: number;
            }[];
        };
        BlocoPrevistoRealizado: {
            total: number;
            lancamentos: number;
            contas: {
                conta?: string | null;
                nome?: string | null;
                /** @description Ex. "AJUSTE (estorno)" */
                detalhe?: string | null;
                valor: number;
                lancamentos: number;
            }[];
        };
        EvidenciaLancamento: {
            /** Format: uuid */
            lancamentoId: string;
            /** Format: date */
            data: string;
            conta?: string | null;
            contaNome?: string | null;
            historico: string;
            fornecedor?: string | null;
            documento?: string | null;
            valor: number;
            fundo?: string | null;
            /** Format: uuid */
            arquivoId: string;
            arquivoNome?: string | null;
            sha256: string;
            pagina: number;
            ordem: number;
            /** @description "realocado para <linha> por <usuário> em <data>" */
            realocacao?: string | null;
        };
        Problema: {
            title?: string;
            status?: number;
            detail?: string;
            /** Format: uuid */
            arquivoExistenteId?: string;
            /** @description Em recusa por módulo não contratado (403): código do módulo */
            modulo?: string;
            /** @description Motivos da recusa da confirmação da PO */
            motivos?: string[];
        };
    };
    responses: never;
    parameters: {
        CondominioId: string;
        ArquivoId: string;
        /** @description Código do módulo no catálogo (ex.: ASSISTENTE) */
        CodigoModulo: string;
        PoId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    eu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioLogado"];
                };
            };
        };
    };
    categorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"][];
                };
            };
        };
    };
    listarArquivos: {
        parameters: {
            query?: {
                categoria?: components["schemas"]["Categoria"];
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"][];
                };
            };
        };
    };
    enviarArquivo: {
        parameters: {
            query: {
                categoria: components["schemas"]["Categoria"];
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    arquivo: string;
                };
            };
        };
        responses: {
            /** @description Recebido e na fila */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo já enviado (mesmo conteúdo) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    ultimoArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Nenhum arquivo ainda */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detalheArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoDetalhe"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    conteudoArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O arquivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    reprocessarArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Na fila */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Já está em processamento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alterarCategoriaArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovaCategoria"];
            };
        };
        responses: {
            /** @description Categoria trocada (arquivo na fila de novo) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Categoria não informada ou inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Já está em processamento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    painel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Painel"];
                };
            };
            /** @description Ainda não há fluxo de caixa processado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmarFundoOrdinario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    fundoId: string;
                };
            };
        };
        responses: {
            /** @description Confirmado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fundo não é deste condomínio */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    contextoCondominio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextoCondominio"];
                };
            };
            /** @description Sem acesso a este condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Condomínio não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listarModulos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK, na ordem do catálogo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuloDoCondominio"][];
                };
            };
            /** @description Sem acesso a este condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alterarModulo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                /** @description Código do módulo no catálogo (ex.: ASSISTENTE) */
                codigo: components["parameters"]["CodigoModulo"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlteracaoModulo"];
            };
        };
        responses: {
            /** @description Estado depois da alteração */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuloDoCondominio"];
                };
            };
            /** @description Estado não informado ou motivo acima de 500 caracteres */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Módulo fora do catálogo ou condomínio não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eventosModulo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                /** @description Código do módulo no catálogo (ex.: ASSISTENTE) */
                codigo: components["parameters"]["CodigoModulo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoModulo"][];
                };
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Módulo fora do catálogo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    periodosModulo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                /** @description Código do módulo no catálogo (ex.: ASSISTENTE) */
                codigo: components["parameters"]["CodigoModulo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK, do mais antigo para o mais recente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodoAtivo"][];
                };
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Módulo fora do catálogo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    usoModulos: {
        parameters: {
            query: {
                inicio: string;
                fim: string;
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsoDoPeriodo"];
                };
            };
            /** @description Datas ausentes ou início depois do fim */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportarUsoModulos: {
        parameters: {
            query: {
                inicio: string;
                fim: string;
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Planilha Excel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            /** @description Datas ausentes ou início depois do fim */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listarPrevisoes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrevisaoResumo"][];
                };
            };
            /** @description Sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detalhePrevisao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrevisaoDetalhe"];
                };
            };
            /** @description Sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmarPrevisao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoConfirmacao"];
            };
        };
        responses: {
            /** @description Confirmada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrevisaoDetalhe"];
                };
            };
            /** @description Perfil sem permissão (Gestor e Usuário) ou sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO já confirmada ou outra PO confirmada vale nos mesmos meses */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            /** @description Confirmação recusada (lista em motivos) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    listarDepara: {
        parameters: {
            query?: {
                filtro?: components["schemas"]["FiltroDepara"];
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeparaLista"];
                };
            };
            /** @description Sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    definirDepara: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
                /** @description Código da conta do fluxo como impresso (ex. 0028) */
                conta: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoDestino"];
            };
        };
        responses: {
            /** @description Gravado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaDepara"];
                };
            };
            /** @description Perfil sem permissão (Gestor e Usuário) ou sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO ainda não confirmada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Destino inválido (linha de outra PO */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loteDepara: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoLote"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoLote"];
                };
            };
            /** @description Perfil sem permissão ou sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO ainda não confirmada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sugerirDepara: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoSugestoes"];
                };
            };
            /** @description Perfil sem permissão ou sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO ainda não confirmada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    planilhaDepara: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    arquivo: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoPlanilha"];
                };
            };
            /** @description Perfil sem permissão ou sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO ainda não confirmada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Planilha acima de 1 MB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eventosDepara: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoDepara"][];
                };
            };
            /** @description Sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PO não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    previstoRealizado: {
        parameters: {
            query: {
                /** @description AAAA-MM ou "acumulado" */
                periodo: string;
                /** @description Versão da PO; sem ela */
                po?: string;
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrevistoRealizado"];
                };
            };
            /** @description Período inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Condomínio ou PO não encontrados */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    evidenciaPrevistoRealizado: {
        parameters: {
            query: {
                periodo: string;
                po?: string;
                /** @description "linha:<linhaId>", "fundo:<fundoId>" (arrecadação), AJUSTES, A_REALOCAR, SEM_LINHA_PO ou TRANSFERENCIAS */
                alvo: string;
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK (lista vazia quando o alvo não tem lançamento) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenciaLancamento"][];
                };
            };
            /** @description Período ou alvo inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
