/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário logado, perfis e condomínios visíveis */
        get: operations["eu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categorias de arquivo, na ordem da tela */
        get: operations["categorias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Arquivos do mais recente para o mais antigo */
        get: operations["listarArquivos"];
        put?: never;
        /** Envia um arquivo (GESTOR ou ADMIN). O processamento segue em segundo plano. */
        post: operations["enviarArquivo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/ultimo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Último arquivo enviado (indicador no canto da tela) */
        get: operations["ultimoArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        /** Detalhe com conferências e saldos por fundo */
        get: operations["detalheArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/conteudo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        /** Arquivo original, exatamente como foi enviado */
        get: operations["conteudoArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/reprocessar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coloca o arquivo de novo na fila (GESTOR ou ADMIN). Não duplica dados. */
        post: operations["reprocessarArquivo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/categoria": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Troca a categoria e reprocessa o arquivo (GESTOR ou ADMIN, RF-01.7). Mesma categoria não faz nada. */
        put: operations["alterarCategoriaArquivo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/painel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Números da tela inicial, do fluxo de caixa mais recente */
        get: operations["painel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/fundo-ordinario": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Confirma qual fundo é o ordinário do condomínio (GESTOR ou ADMIN) */
        put: operations["confirmarFundoOrdinario"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** POs lidas do condomínio, da mais recente para a mais antiga (todos os perfis, RF-03.1.1) */
        get: operations["listarPrevisoes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/previsoes/{poId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        /** PO com linhas, conferências, avisos e pendências (todos os perfis, RF-03.1.1 e RF-03.1.2) */
        get: operations["detalhePrevisao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Categoria: "BALANCETE" | "EXTRATO" | "PO" | "CONTRATO" | "FOLHA" | "COMPROVANTE" | "ATA" | "CONVENCAO_RI" | "OUTROS";
        NovaCategoria: {
            categoria: components["schemas"]["Categoria"];
        };
        /** @enum {string} */
        StatusArquivo: "PENDENTE" | "PROCESSANDO" | "CONCLUIDO" | "PRECISA_REVISAO" | "FALHOU";
        CategoriaDto: {
            codigo: components["schemas"]["Categoria"];
            rotulo: string;
        };
        UsuarioLogado: {
            usuario: string;
            nome: string;
            perfis: ("USUARIO" | "GESTOR" | "ADMIN")[];
            condominios: {
                /** Format: uuid */
                id: string;
                nome: string;
            }[];
        };
        ArquivoResumo: {
            /** Format: uuid */
            id: string;
            categoria: components["schemas"]["Categoria"];
            categoriaRotulo: string;
            nome: string;
            /** Format: int64 */
            tamanhoBytes: number;
            status: components["schemas"]["StatusArquivo"];
            mensagem?: string | null;
            /** Format: date */
            periodoInicio?: string | null;
            /** Format: date */
            periodoFim?: string | null;
            totalLancamentos?: number | null;
            enviadoPor: string;
            /** Format: date-time */
            enviadoEm: string;
            /** Format: date-time */
            processadoEm?: string | null;
        };
        ArquivoDetalhe: {
            arquivo: components["schemas"]["ArquivoResumo"];
            sha256: string;
            conferencias: {
                codigo: string;
                descricao: string;
                ok: boolean;
                detalhe?: string | null;
            }[];
            fundos: {
                fundo: string;
                saldoAnterior: number;
                creditos: number;
                debitos: number;
                saldoAtual: number;
            }[];
        };
        Painel: {
            /** Format: uuid */
            arquivoId: string;
            arquivoNome: string;
            /** Format: date */
            periodoInicio: string;
            /** Format: date */
            periodoFim: string;
            saldoAnterior: number;
            entradas: number;
            saidas: number;
            saldoAtual: number;
            conferenciasComFalha: number;
            /**
             * @description Saldo acumulado do fundo ordinário (cartão "Saldo acumulado"). Com confirmado=false é só a sugestão
             *     (fundo com mais entradas no mês), que a tela mostra para o Gestor confirmar. Nulo quando não há sugestão.
             */
            fundoOrdinario: null | {
                /** Format: uuid */
                fundoId: string;
                fundo: string;
                confirmado: boolean;
                /** @description Nulo quando o fundo confirmado não está no relatório */
                saldoAtual: number | null;
            };
            fundos: {
                /** Format: uuid */
                fundoId: string;
                fundo: string;
                saldoAnterior: number;
                entradas: number;
                saidas: number;
                resultado: number;
                saldoAtual: number;
            }[];
            maioresDespesas: {
                /** Format: date */
                data: string;
                fundo: string;
                conta: string;
                historico: string;
                valor: number;
                pagina: number;
            }[];
        };
        /**
         * @description LIDA (aguarda confirmação), LIDA_COM_DIVERGENCIA (soma que não bate além da tolerância de arredondamento),
         *     CONFIRMADA (vale para os meses do exercício) e SUBSTITUIDA (trocada por reaprovação a partir de um mês).
         * @enum {string}
         */
        EstadoPrevisao: "LIDA" | "LIDA_COM_DIVERGENCIA" | "CONFIRMADA" | "SUBSTITUIDA";
        PrevisaoResumo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            arquivoId: string;
            arquivoNome?: string | null;
            sha256: string;
            estado: components["schemas"]["EstadoPrevisao"];
            /** @description Preenchida na confirmação (1 */
            versao?: number | null;
            titulo?: string | null;
            /** @description Como impresso (ex. "2026 / 2027") */
            exercicioImpresso?: string | null;
            /** @description AAAA-MM */
            exercicioInicio?: string | null;
            exercicioFim?: string | null;
            totalImpresso?: number | null;
            /** @description Soma das linhas dos grupos que não são fundos (usada nos cálculos) */
            previstoMes: number;
            /** Format: date-time */
            lidaEm: string;
            confirmadaPor?: string | null;
            /** Format: date-time */
            confirmadaEm?: string | null;
        };
        PrevisaoDetalhe: {
            previsao: components["schemas"]["PrevisaoResumo"];
            colunaOrcadoAnterior?: string | null;
            colunaOrcado?: string | null;
            /** @description Total impresso menos fundos impressos */
            previstoMesImpresso?: number | null;
            /** @description Diferença máxima tratada como arredondamento nesta leitura */
            toleranciaArredondamento: number;
            /** @description Mês a partir do qual vale a nova versão */
            substituidaDesde?: string | null;
            /** @description Dados informados pelo Admin; nulo antes da confirmação */
            confirmacao?: null | {
                /** Format: uuid */
                ataArquivoId?: string | null;
                semAta: boolean;
                /** Format: date */
                dataAprovacao?: string | null;
                cienteDivergencia: boolean;
                justificativaDivergencia?: string | null;
            };
            linhas: components["schemas"]["LinhaPo"][];
            conferencias: components["schemas"]["ConferenciaPo"][];
            avisos: components["schemas"]["AvisoPo"][];
            codigosRepetidos: {
                codigoImpresso: string;
                /** @description Os códigos efetivos dessas linhas já são distintos */
                resolvido: boolean;
                linhas: {
                    /** Format: uuid */
                    linhaId: string;
                    ordem: number;
                    descricao: string;
                    codigoEfetivo: string;
                }[];
            }[];
            /** @description Ligação das linhas de fundo (1.9.x) aos fundos do fluxo, feita na confirmação */
            fundos: {
                /** Format: uuid */
                linhaId: string;
                codigoEfetivo: string;
                descricao: string;
                orcado: number;
                /** Format: uuid */
                fundoId: string;
                fundo: string;
            }[];
            achados: {
                /** Format: uuid */
                id: string;
                regra: string;
                versaoRegra: string;
                /** @enum {string} */
                severidade: "INFORMATIVO" | "ATENCAO" | "CRITICO";
                competencia: string;
                descricao: string;
                /** @enum {string} */
                estado: "ABERTO";
            }[];
        };
        LinhaPo: {
            /**
             * Format: uuid
             * @description Identificador estável da linha (destino do de-para)
             */
            id: string;
            ordem: number;
            pagina: number;
            /** @enum {string} */
            tipo: "TOTAL" | "GRUPO" | "LINHA";
            codigoImpresso: string;
            /** @description Igual ao impresso; o Admin muda só quando o código se repete */
            codigoEfetivo: string;
            conta?: string | null;
            contaTexto?: string | null;
            /** @enum {string|null} */
            marca?: "RATEIO_A_PARTE" | "NEGOCIADA_ISENCAO" | "SEM_VALOR" | "VALOR_FIXO_SEM_REFERENCIA" | null;
            descricao: string;
            orcadoAnterior: number;
            orcado: number;
            /** @description Coluna "%" como lida; não entra em cálculo */
            percentualTexto?: string | null;
            observacoes?: string | null;
            /** @description Linha do grupo de fundos (precisa ser ligada a um fundo na confirmação) */
            linhaDeFundo: boolean;
            /** Format: uuid */
            arquivoId: string;
            sha256: string;
        };
        ConferenciaPo: {
            codigo: string;
            descricao: string;
            ok: boolean;
            detalhe?: string | null;
            /**
             * @description OK; ARREDONDAMENTO (diferença até a tolerância, só aviso); DIVERGENCIA; CODIGO_REPETIDO (pendência)
             * @enum {string}
             */
            classificacao: "OK" | "ARREDONDAMENTO" | "DIVERGENCIA" | "CODIGO_REPETIDO";
            /** @description Quando falhou */
            explicacao?: string | null;
        };
        AvisoPo: {
            /** @enum {string} */
            codigo: "ARREDONDAMENTO" | "DIVERGENCIA" | "CODIGO_REPETIDO" | "CONFIRMADA_COM_DIVERGENCIA" | "FORA_PRIMEIRO_TRIMESTRE" | "SEM_ATA" | "REGRA_NAO_AVALIADA";
            texto: string;
        };
        Problema: {
            title?: string;
            status?: number;
            detail?: string;
            /** Format: uuid */
            arquivoExistenteId?: string;
        };
    };
    responses: never;
    parameters: {
        CondominioId: string;
        ArquivoId: string;
        PoId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    eu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioLogado"];
                };
            };
        };
    };
    categorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"][];
                };
            };
        };
    };
    listarArquivos: {
        parameters: {
            query?: {
                categoria?: components["schemas"]["Categoria"];
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"][];
                };
            };
        };
    };
    enviarArquivo: {
        parameters: {
            query: {
                categoria: components["schemas"]["Categoria"];
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    arquivo: string;
                };
            };
        };
        responses: {
            /** @description Recebido e na fila */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo já enviado (mesmo conteúdo) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    ultimoArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Nenhum arquivo ainda */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detalheArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoDetalhe"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    conteudoArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O arquivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    reprocessarArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Na fila */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Já está em processamento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alterarCategoriaArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovaCategoria"];
            };
        };
        responses: {
            /** @description Categoria trocada (arquivo na fila de novo) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Categoria não informada ou inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Já está em processamento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    painel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Painel"];
                };
            };
            /** @description Ainda não há fluxo de caixa processado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmarFundoOrdinario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    fundoId: string;
                };
            };
        };
        responses: {
            /** @description Confirmado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fundo não é deste condomínio */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listarPrevisoes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrevisaoResumo"][];
                };
            };
            /** @description Sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detalhePrevisao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                poId: components["parameters"]["PoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrevisaoDetalhe"];
                };
            };
            /** @description Sem acesso ao condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
