/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário logado, perfis e condomínios visíveis */
        get: operations["eu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categorias de arquivo, na ordem da tela */
        get: operations["categorias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Arquivos do mais recente para o mais antigo */
        get: operations["listarArquivos"];
        put?: never;
        /** Envia um arquivo (GESTOR ou ADMIN). O processamento segue em segundo plano. */
        post: operations["enviarArquivo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/ultimo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Último arquivo enviado (indicador no canto da tela) */
        get: operations["ultimoArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        /** Detalhe com conferências e saldos por fundo */
        get: operations["detalheArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/conteudo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        /** Arquivo original, exatamente como foi enviado */
        get: operations["conteudoArquivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/reprocessar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coloca o arquivo de novo na fila de leitura e de indexação (GESTOR ou ADMIN). Não duplica dados. */
        post: operations["reprocessarArquivo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/arquivos/{id}/categoria": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Troca a categoria e reprocessa o arquivo (GESTOR ou ADMIN, RF-01.7). Mesma categoria não faz nada. */
        put: operations["alterarCategoriaArquivo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/painel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /** Números da tela inicial, do fluxo de caixa mais recente */
        get: operations["painel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/fundo-ordinario": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Confirma qual fundo é o ordinário do condomínio (GESTOR ou ADMIN) */
        put: operations["confirmarFundoOrdinario"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Categoria: "BALANCETE" | "EXTRATO" | "PO" | "CONTRATO" | "FOLHA" | "COMPROVANTE" | "ATA" | "CONVENCAO_RI" | "OUTROS";
        NovaCategoria: {
            categoria: components["schemas"]["Categoria"];
        };
        /** @enum {string} */
        StatusArquivo: "PENDENTE" | "PROCESSANDO" | "CONCLUIDO" | "PRECISA_REVISAO" | "FALHOU";
        CategoriaDto: {
            codigo: components["schemas"]["Categoria"];
            rotulo: string;
        };
        UsuarioLogado: {
            usuario: string;
            nome: string;
            perfis: ("USUARIO" | "GESTOR" | "ADMIN")[];
            condominios: {
                /** Format: uuid */
                id: string;
                nome: string;
            }[];
        };
        ArquivoResumo: {
            /** Format: uuid */
            id: string;
            categoria: components["schemas"]["Categoria"];
            categoriaRotulo: string;
            nome: string;
            /** Format: int64 */
            tamanhoBytes: number;
            status: components["schemas"]["StatusArquivo"];
            mensagem?: string | null;
            /** Format: date */
            periodoInicio?: string | null;
            /** Format: date */
            periodoFim?: string | null;
            totalLancamentos?: number | null;
            enviadoPor: string;
            /** Format: date-time */
            enviadoEm: string;
            /** Format: date-time */
            processadoEm?: string | null;
            /** @description Estado da indexação para a busca nos documentos (ADR 0003). Nulo ou ausente = arquivo ainda não indexado (enviado antes da busca; reprocessar indexa). */
            indexacao?: components["schemas"]["IndexacaoArquivo"] | null;
        };
        /**
         * @description NA_FILA e INDEXANDO = em andamento; INDEXADO = aparece na busca; SEM_TEXTO = sem texto extraível (ex. PDF digitalizado); RETIRADO = fora da busca (exclusão lógica ou versão substituída); ERRO = falhou (ver motivo).
         * @enum {string}
         */
        SituacaoIndexacao: "NA_FILA" | "INDEXANDO" | "INDEXADO" | "SEM_TEXTO" | "RETIRADO" | "ERRO";
        IndexacaoArquivo: {
            situacao: components["schemas"]["SituacaoIndexacao"];
            /** @description Preenchido em SEM_TEXTO e ERRO */
            motivo?: string | null;
            /** @description Páginas (PDF), abas (Excel) ou 1 (Word) lidas */
            paginas?: number | null;
            /** @description Trechos gravados no índice */
            trechos?: number | null;
        };
        ArquivoDetalhe: {
            arquivo: components["schemas"]["ArquivoResumo"];
            sha256: string;
            conferencias: {
                codigo: string;
                descricao: string;
                ok: boolean;
                detalhe?: string | null;
            }[];
            fundos: {
                fundo: string;
                saldoAnterior: number;
                creditos: number;
                debitos: number;
                saldoAtual: number;
            }[];
        };
        Painel: {
            /** Format: uuid */
            arquivoId: string;
            arquivoNome: string;
            /** Format: date */
            periodoInicio: string;
            /** Format: date */
            periodoFim: string;
            saldoAnterior: number;
            entradas: number;
            saidas: number;
            saldoAtual: number;
            conferenciasComFalha: number;
            /**
             * @description Saldo acumulado do fundo ordinário (cartão "Saldo acumulado"). Com confirmado=false é só a sugestão
             *     (fundo com mais entradas no mês), que a tela mostra para o Gestor confirmar. Nulo quando não há sugestão.
             */
            fundoOrdinario: null | {
                /** Format: uuid */
                fundoId: string;
                fundo: string;
                confirmado: boolean;
                /** @description Nulo quando o fundo confirmado não está no relatório */
                saldoAtual: number | null;
            };
            fundos: {
                /** Format: uuid */
                fundoId: string;
                fundo: string;
                saldoAnterior: number;
                entradas: number;
                saidas: number;
                resultado: number;
                saldoAtual: number;
            }[];
            maioresDespesas: {
                /** Format: date */
                data: string;
                fundo: string;
                conta: string;
                historico: string;
                valor: number;
                pagina: number;
            }[];
        };
        Problema: {
            title?: string;
            status?: number;
            detail?: string;
            /** Format: uuid */
            arquivoExistenteId?: string;
        };
    };
    responses: never;
    parameters: {
        CondominioId: string;
        ArquivoId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    eu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioLogado"];
                };
            };
        };
    };
    categorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"][];
                };
            };
        };
    };
    listarArquivos: {
        parameters: {
            query?: {
                categoria?: components["schemas"]["Categoria"];
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"][];
                };
            };
        };
    };
    enviarArquivo: {
        parameters: {
            query: {
                categoria: components["schemas"]["Categoria"];
            };
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    arquivo: string;
                };
            };
        };
        responses: {
            /** @description Recebido e na fila */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo já enviado (mesmo conteúdo) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    ultimoArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Nenhum arquivo ainda */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detalheArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoDetalhe"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    conteudoArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O arquivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    reprocessarArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Na fila */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Já está em processamento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alterarCategoriaArquivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
                id: components["parameters"]["ArquivoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovaCategoria"];
            };
        };
        responses: {
            /** @description Categoria trocada (arquivo na fila de novo) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArquivoResumo"];
                };
            };
            /** @description Categoria não informada ou inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Já está em processamento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    painel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Painel"];
                };
            };
            /** @description Ainda não há fluxo de caixa processado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmarFundoOrdinario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    fundoId: string;
                };
            };
        };
        responses: {
            /** @description Confirmado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fundo não é deste condomínio */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
