-- ADR 0006, fase 2: tabelas e colunas do api em inglês. Só renomeia: nenhum dado muda.
-- Índices, restrições e gatilhos acompanham a tabela e mantêm o nome antigo.

alter table achado rename column condominio_id to condominium_id;
alter table achado rename column regra to rule;
alter table achado rename column versao_regra to rule_version;
alter table achado rename column severidade to severity;
alter table achado rename column competencia to reference_month;
alter table achado rename column alvo to target;
alter table achado rename column descricao to description;
alter table achado rename column estado to status;
alter table achado rename column criado_em to created_at;
alter table achado rename column condicao_presente to condition_present;
alter table achado rename column estado_motivo to status_reason;
alter table achado rename column estado_em to status_changed_at;
alter table achado rename to finding;

alter table achado_evidencia rename column achado_id to finding_id;
alter table achado_evidencia rename column ordem to position;
alter table achado_evidencia rename column arquivo_id to file_id;
alter table achado_evidencia rename column pagina to page;
alter table achado_evidencia rename column referencia to reference;
alter table achado_evidencia rename column linha_po_id to budget_line_id;
alter table achado_evidencia rename to finding_evidence;

alter table arquivo rename column condominio_id to condominium_id;
alter table arquivo rename column categoria to category;
alter table arquivo rename column nome_original to original_name;
alter table arquivo rename column caminho to path;
alter table arquivo rename column tamanho_bytes to size_bytes;
alter table arquivo rename column tipo_conteudo to content_type;
alter table arquivo rename column mensagem to message;
alter table arquivo rename column interpretador to parser;
alter table arquivo rename column periodo_inicio to period_start;
alter table arquivo rename column periodo_fim to period_end;
alter table arquivo rename column total_lancamentos to entry_count;
alter table arquivo rename column enviado_por to uploaded_by;
alter table arquivo rename column enviado_em to uploaded_at;
alter table arquivo rename column processado_em to processed_at;
alter table arquivo rename column processamento_id to processing_id;
alter table arquivo rename column enfileirado_em to queued_at;
alter table arquivo rename column tentativas to attempts;
alter table arquivo rename column indexacao_situacao to indexing_status;
alter table arquivo rename column indexacao_motivo to indexing_reason;
alter table arquivo rename column indexacao_paginas to indexing_pages;
alter table arquivo rename column indexacao_trechos to indexing_chunks;
alter table arquivo rename column indexacao_id to indexing_id;
alter table arquivo rename column indexacao_enfileirada_em to indexing_queued_at;
alter table arquivo rename column indexacao_tentativas to indexing_attempts;
alter table arquivo rename column indexacao_atualizada_em to indexing_updated_at;
alter table arquivo rename to source_file;

alter table arquivo_categoria_historico rename column arquivo_id to file_id;
alter table arquivo_categoria_historico rename column categoria_anterior to previous_category;
alter table arquivo_categoria_historico rename column categoria_nova to new_category;
alter table arquivo_categoria_historico rename column alterado_por to changed_by;
alter table arquivo_categoria_historico rename column alterado_em to changed_at;
alter table arquivo_categoria_historico rename to category_change;

alter table condominio rename column nome to name;
alter table condominio rename column criado_em to created_at;
alter table condominio rename column fundo_ordinario_id to operating_fund_id;
alter table condominio rename column fundo_ordinario_confirmado_por to operating_fund_confirmed_by;
alter table condominio rename column fundo_ordinario_confirmado_em to operating_fund_confirmed_at;
alter table condominio rename to condominium;

alter table conferencia rename column arquivo_id to file_id;
alter table conferencia rename column ordem to sequence;
alter table conferencia rename column codigo to code;
alter table conferencia rename column descricao to description;
alter table conferencia rename column detalhe to detail;
alter table conferencia rename to totals_check;

alter table configuracao_ia rename column condominio_id to condominium_id;
alter table configuracao_ia rename column modulo to feature;
alter table configuracao_ia rename column funcao to function;
alter table configuracao_ia rename column modo to mode;
alter table configuracao_ia rename column provedor to provider;
alter table configuracao_ia rename column modelo to model;
alter table configuracao_ia rename column chave_cifrada to encrypted_key;
alter table configuracao_ia rename column chave_final to key_suffix;
alter table configuracao_ia rename column atualizado_por to updated_by;
alter table configuracao_ia rename column atualizado_em to updated_at;
alter table configuracao_ia rename to ai_configuration;

alter table depara_conta rename column condominio_id to condominium_id;
alter table depara_conta rename column previsao_id to budget_id;
alter table depara_conta rename column conta_codigo to account_code;
alter table depara_conta rename column conta_nome to account_name;
alter table depara_conta rename column tipo_destino to target_type;
alter table depara_conta rename column linha_po_id to budget_line_id;
alter table depara_conta rename column detalhe_destino to target_detail;
alter table depara_conta rename column estado to status;
alter table depara_conta rename column origem to source;
alter table depara_conta rename column motivo to reason;
alter table depara_conta rename column igual_versao_anterior to same_as_previous_version;
alter table depara_conta rename column atualizado_por to updated_by;
alter table depara_conta rename column atualizado_em to updated_at;
alter table depara_conta rename to account_mapping;

alter table evento_achado rename column achado_id to finding_id;
alter table evento_achado rename column condominio_id to condominium_id;
alter table evento_achado rename column estado_anterior to previous_status;
alter table evento_achado rename column estado_novo to new_status;
alter table evento_achado rename column condicao_presente to condition_present;
alter table evento_achado rename column motivo to reason;
alter table evento_achado rename column usuario to username;
alter table evento_achado rename column em to occurred_at;
alter table evento_achado rename to finding_event;

alter table evento_configuracao_ia rename column condominio_id to condominium_id;
alter table evento_configuracao_ia rename column modulo to feature;
alter table evento_configuracao_ia rename column funcao to function;
alter table evento_configuracao_ia rename column usuario to username;
alter table evento_configuracao_ia rename column quando to occurred_at;
alter table evento_configuracao_ia rename column modo_anterior to previous_mode;
alter table evento_configuracao_ia rename column modo_novo to new_mode;
alter table evento_configuracao_ia rename column provedor_anterior to previous_provider;
alter table evento_configuracao_ia rename column provedor_novo to new_provider;
alter table evento_configuracao_ia rename column modelo_anterior to previous_model;
alter table evento_configuracao_ia rename column modelo_novo to new_model;
alter table evento_configuracao_ia rename column chave_trocada to key_replaced;
alter table evento_configuracao_ia rename column chave_final to key_suffix;
alter table evento_configuracao_ia rename to ai_configuration_event;

alter table evento_depara rename column condominio_id to condominium_id;
alter table evento_depara rename column previsao_id to budget_id;
alter table evento_depara rename column conta_codigo to account_code;
alter table evento_depara rename column conta_nome to account_name;
alter table evento_depara rename column acao to action;
alter table evento_depara rename column usuario to username;
alter table evento_depara rename column em to occurred_at;
alter table evento_depara rename column tipo_destino_anterior to previous_target_type;
alter table evento_depara rename column linha_po_anterior_id to previous_budget_line_id;
alter table evento_depara rename column destino_anterior to previous_target;
alter table evento_depara rename column estado_anterior to previous_status;
alter table evento_depara rename column tipo_destino_novo to new_target_type;
alter table evento_depara rename column linha_po_nova_id to new_budget_line_id;
alter table evento_depara rename column destino_novo to new_target;
alter table evento_depara rename column estado_novo to new_status;
alter table evento_depara rename column origem to source;
alter table evento_depara rename column motivo to reason;
alter table evento_depara rename to account_mapping_event;

alter table evento_modulo rename column condominio_id to condominium_id;
alter table evento_modulo rename column modulo to feature;
alter table evento_modulo rename column ligado_antes to enabled_before;
alter table evento_modulo rename column ligado_depois to enabled_after;
alter table evento_modulo rename column usuario to username;
alter table evento_modulo rename column quando to occurred_at;
alter table evento_modulo rename column motivo to reason;
alter table evento_modulo rename to feature_event;

alter table evento_previsao rename column previsao_id to budget_id;
alter table evento_previsao rename column condominio_id to condominium_id;
alter table evento_previsao rename column tipo to type;
alter table evento_previsao rename column usuario to username;
alter table evento_previsao rename column em to occurred_at;
alter table evento_previsao rename column justificativa to justification;
alter table evento_previsao rename column detalhe to detail;
alter table evento_previsao rename to budget_event;

alter table evento_realocacao rename column realocacao_id to reallocation_id;
alter table evento_realocacao rename column condominio_id to condominium_id;
alter table evento_realocacao rename column acao to action;
alter table evento_realocacao rename column usuario to username;
alter table evento_realocacao rename column em to occurred_at;
alter table evento_realocacao rename column detalhe to detail;
alter table evento_realocacao rename to reallocation_event;

alter table evento_rubrica rename column condominio_id to condominium_id;
alter table evento_rubrica rename column previsao_id to budget_id;
alter table evento_rubrica rename column linha_po_id to budget_line_id;
alter table evento_rubrica rename column linha_codigo to line_code;
alter table evento_rubrica rename column linha_descricao to line_description;
alter table evento_rubrica rename column acao to action;
alter table evento_rubrica rename column usuario to username;
alter table evento_rubrica rename column em to occurred_at;
alter table evento_rubrica rename column rubrica_anterior_id to previous_item_id;
alter table evento_rubrica rename column rubrica_anterior to previous_item;
alter table evento_rubrica rename column estado_anterior to previous_status;
alter table evento_rubrica rename column rubrica_nova_id to new_item_id;
alter table evento_rubrica rename column rubrica_nova to new_item;
alter table evento_rubrica rename column estado_novo to new_status;
alter table evento_rubrica rename column origem to source;
alter table evento_rubrica rename column motivo to reason;
alter table evento_rubrica rename to budget_item_event;

alter table fundo rename column condominio_id to condominium_id;
alter table fundo rename column nome to name;
alter table fundo rename to fund;

alter table lancamento rename column condominio_id to condominium_id;
alter table lancamento rename column arquivo_id to file_id;
alter table lancamento rename column fundo_id to fund_id;
alter table lancamento rename column data to date;
alter table lancamento rename column conta_codigo to account_code;
alter table lancamento rename column conta_nome to account_name;
alter table lancamento rename column documento to document;
alter table lancamento rename column historico to memo;
alter table lancamento rename column credito to credit;
alter table lancamento rename column debito to debit;
alter table lancamento rename column saldo to balance;
alter table lancamento rename column pagina to page;
alter table lancamento rename column ordem to sequence;
alter table lancamento rename column nota_fiscal to invoice_number;
alter table lancamento rename column fornecedor to supplier;
alter table lancamento rename column meio_pagamento to payment_method;
alter table lancamento rename column transferencia_entre_fundos to inter_fund_transfer;
alter table lancamento rename column recebimento_cota to condo_fee_receipt;
alter table lancamento rename to ledger_entry;

alter table linha_po rename column previsao_id to budget_id;
alter table linha_po rename column condominio_id to condominium_id;
alter table linha_po rename column arquivo_id to file_id;
alter table linha_po rename column ordem to position;
alter table linha_po rename column pagina to page;
alter table linha_po rename column tipo to type;
alter table linha_po rename column codigo_impresso to printed_code;
alter table linha_po rename column codigo_efetivo to effective_code;
alter table linha_po rename column conta to account;
alter table linha_po rename column conta_texto to account_text;
alter table linha_po rename column marca to mark;
alter table linha_po rename column descricao to description;
alter table linha_po rename column orcado_anterior to previous_budgeted;
alter table linha_po rename column orcado to budgeted;
alter table linha_po rename column percentual_texto to percentage_text;
alter table linha_po rename column observacoes to notes;
alter table linha_po rename to budget_line;

alter table linha_rubrica rename column condominio_id to condominium_id;
alter table linha_rubrica rename column previsao_id to budget_id;
alter table linha_rubrica rename column linha_po_id to budget_line_id;
alter table linha_rubrica rename column rubrica_id to budget_item_id;
alter table linha_rubrica rename column estado to status;
alter table linha_rubrica rename column origem to source;
alter table linha_rubrica rename column motivo to reason;
alter table linha_rubrica rename column atualizado_por to updated_by;
alter table linha_rubrica rename column atualizado_em to updated_at;
alter table linha_rubrica rename to budget_line_item;

alter table modulo_condominio rename column ligado to enabled;
alter table modulo_condominio rename column desde to since;
alter table modulo_condominio rename column alterado_por to changed_by;
alter table modulo_condominio rename column condominio_id to condominium_id;
alter table modulo_condominio rename column modulo to feature;
alter table modulo_condominio rename to condominium_feature;

alter table parametro_regra rename column condominio_id to condominium_id;
alter table parametro_regra rename column codigo to code;
alter table parametro_regra rename column valor to value;
alter table parametro_regra rename column vigente_desde to valid_from;
alter table parametro_regra rename column vigente_ate to valid_to;
alter table parametro_regra rename column fonte to source;
alter table parametro_regra rename to rule_parameter;

alter table po_fundo rename column previsao_id to budget_id;
alter table po_fundo rename column linha_po_id to budget_line_id;
alter table po_fundo rename column fundo_id to fund_id;
alter table po_fundo rename to budget_fund_link;

alter table previsao_orcamentaria rename column condominio_id to condominium_id;
alter table previsao_orcamentaria rename column arquivo_id to file_id;
alter table previsao_orcamentaria rename column interpretador to parser;
alter table previsao_orcamentaria rename column titulo to title;
alter table previsao_orcamentaria rename column exercicio_impresso to printed_fiscal_year;
alter table previsao_orcamentaria rename column coluna_orcado_anterior to previous_budgeted_column;
alter table previsao_orcamentaria rename column coluna_orcado to budgeted_column;
alter table previsao_orcamentaria rename column estado to status;
alter table previsao_orcamentaria rename column total_impresso to printed_total;
alter table previsao_orcamentaria rename column previsto_mes_impresso to printed_monthly_planned;
alter table previsao_orcamentaria rename column previsto_mes to monthly_planned;
alter table previsao_orcamentaria rename column tolerancia_arredondamento to rounding_tolerance;
alter table previsao_orcamentaria rename column lida_em to read_at;
alter table previsao_orcamentaria rename column versao to version;
alter table previsao_orcamentaria rename column exercicio_inicio to fiscal_year_start;
alter table previsao_orcamentaria rename column exercicio_fim to fiscal_year_end;
alter table previsao_orcamentaria rename column substituida_desde to superseded_from;
alter table previsao_orcamentaria rename column ata_arquivo_id to minutes_file_id;
alter table previsao_orcamentaria rename column sem_ata to without_minutes;
alter table previsao_orcamentaria rename column data_aprovacao to approval_date;
alter table previsao_orcamentaria rename column ciente_divergencia to discrepancy_acknowledged;
alter table previsao_orcamentaria rename column justificativa_divergencia to discrepancy_justification;
alter table previsao_orcamentaria rename column confirmada_por to confirmed_by;
alter table previsao_orcamentaria rename column confirmada_em to confirmed_at;
alter table previsao_orcamentaria rename column prorrogada_ate to extended_until;
alter table previsao_orcamentaria rename column prorrogacao_justificativa to extension_justification;
alter table previsao_orcamentaria rename column prorrogada_por to extended_by;
alter table previsao_orcamentaria rename column prorrogada_em to extended_at;
alter table previsao_orcamentaria rename to budget;

alter table realocacao rename column condominio_id to condominium_id;
alter table realocacao rename column previsao_id to budget_id;
alter table realocacao rename column chave_lancamento to entry_key;
alter table realocacao rename column arquivo_id to file_id;
alter table realocacao rename column pagina to page;
alter table realocacao rename column ordem to position;
alter table realocacao rename column data to date;
alter table realocacao rename column conta_codigo to account_code;
alter table realocacao rename column conta_nome to account_name;
alter table realocacao rename column documento to document;
alter table realocacao rename column historico to memo;
alter table realocacao rename column valor to amount;
alter table realocacao rename column linha_po_id to budget_line_id;
alter table realocacao rename column realocada_por to reallocated_by;
alter table realocacao rename column realocada_em to reallocated_at;
alter table realocacao rename column desfeita_por to undone_by;
alter table realocacao rename column desfeita_em to undone_at;
alter table realocacao rename to reallocation;

alter table rubrica rename column condominio_id to condominium_id;
alter table rubrica rename column nome to name;
alter table rubrica rename column grupo_codigo to group_code;
alter table rubrica rename column linha_origem_id to source_line_id;
alter table rubrica rename column criada_por to created_by;
alter table rubrica rename column criada_em to created_at;
alter table rubrica rename to budget_item;

alter table saldo_fundo rename column condominio_id to condominium_id;
alter table saldo_fundo rename column arquivo_id to file_id;
alter table saldo_fundo rename column fundo_id to fund_id;
alter table saldo_fundo rename column periodo_inicio to period_start;
alter table saldo_fundo rename column periodo_fim to period_end;
alter table saldo_fundo rename column saldo_anterior to opening_balance;
alter table saldo_fundo rename column creditos to credits;
alter table saldo_fundo rename column debitos to debits;
alter table saldo_fundo rename column saldo_atual to closing_balance;
alter table saldo_fundo rename to fund_balance;

alter table uso_modulo rename column condominio_id to condominium_id;
alter table uso_modulo rename column modulo to feature;
alter table uso_modulo rename column funcao to function;
alter table uso_modulo rename column usuario to username;
alter table uso_modulo rename column quando to occurred_at;
alter table uso_modulo rename column modo to mode;
alter table uso_modulo rename column provedor to provider;
alter table uso_modulo rename column modelo to model;
alter table uso_modulo rename column tokens_entrada to input_tokens;
alter table uso_modulo rename column tokens_saida to output_tokens;
alter table uso_modulo rename column arquivos to files;
alter table uso_modulo rename column paginas to pages;
alter table uso_modulo rename column versao_prompt to prompt_version;
alter table uso_modulo rename to feature_usage;
