package br.com.condominioauditoria.api.service.audit;

import java.text.Normalizer;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Conduct terms forbidden in texts generated by the system outside a literal quote (RF-04.15; initial list decided by
 * the user on 03/10/2026, Q11). The list only grows by the user's decision. Used in the tests of screens, warnings,
 * findings and exports (RF-03.1.12).
 */
public final class ConductTerms {

    public static final List<String> LIST = List.of("desvio", "fraude", "roubo", "culpa");

    private static final Pattern TERM = Pattern.compile("\\b(desvios?|fraudes?|roubos?|culpas?)\\b");

    private ConductTerms() {
    }

    /** Occurrences of the listed terms, singular or plural (accents removed, case insensitive). */
    public static List<String> find(String text) {
        if (text == null || text.isEmpty()) {
            return List.of();
        }
        String normalized = Normalizer.normalize(text, Normalizer.Form.NFD).replaceAll("\\p{M}", "")
                .toLowerCase(Locale.ROOT);
        Matcher m = TERM.matcher(normalized);
        java.util.ArrayList<String> findings = new java.util.ArrayList<>();
        while (m.find()) {
            findings.add(m.group());
        }
        return List.copyOf(findings);
    }
}
